version: "3"

services:
  addreality_test:
    build:
      context: .
      dockerfile: Dockerfile_test
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - PORT=8080
      - METRICS_PORT=8081