version: "3"

services:
  addreality:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - PORT=8080
      - METRICS_PORT=8081