# Image page: <https://hub.docker.com/_/golang>
FROM golang:1.15-alpine as builder
COPY . /src
WORKDIR /src
RUN go build -ldflags="-s -w" -o /tmp/app cmd/main.go

FROM alpine:latest
COPY --from=builder /tmp/app /bin/app
